---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-dns
  namespace: kube-system
spec:
  encryptedData:
    CF_DNS_API_TOKEN: AgAWoPIJy4t4P2Pk2XxFSxnv0g2gubWMZS/2E5/pYh42EXylpw/JuVhW5aRGCdn4m4xLySvb+IASN8zfbShMIZ/8edrcqmdhVZRtiHCgrKb2YUJGRLPjxklz3A4BMDu9VhEEgQrL5ANYSdPSPLMneQ1k62ZXkA1PR9zyxppjsh4cJqaQ6zAECeH9ifZBqgF2hy8PPd+hlwMFSHapEsaIF1vqqMmHpdz/RIYP+L0dwx/QSPty8CArNcGW32EA8inS6pIrV0NweN09gQllMQAEWop4YkqQgsLNip263XmGwhIpki/lzhkL1kapJxpnWGZBuDNL8W9UYzvG1l65jZGC6oyeAAD6BbdzURp6vJehfCJlWySa/R9ikucmCt+zgIrfFbYrOc1jVFsMprLFIblc9lCdpCEv1yLZafaLWri3MreKiIlo9VfixGzkQvgDW2yKk6y7usGm0xTJs+psbwU/XA1JgPTCQlaMPeJXXPCk3ebgyJ3GxHUcPxJMc86YHpzvEonazo+TahyVkfT3pIk1gXWso+OeSBHEKeJmzdWlp+DHjaxyd9xmr2oeFTMymvakfXUsOIdyCZSd4f+J8ODlF2QJ/rcToCgEjU54zg3H73tsXop7t+8bpLuUyB1AGr+uK3HmCWBirR1jPWVGWcmUyIbAHZc278uPYDNgxCHCtPHtLxLaZybY+d0TZ17kc6W1280cGoLc+Y0Mnxycnnl+K1BAzlEaaW3PnlE/0GAnTZ9d/GOUIth+cXXg
  template:
    metadata:
      name: cloudflare-dns
      namespace: kube-system
