apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - argocd-image-updater-install.yaml
  # - argocd-image-updater-config.yaml
  - sealed-secrets.yaml
  - repo-mobilebrain-manifests-sealed-secrets.yaml
  - argocd-notifications-sealed-secrets.yaml
  - argocd-traefik-ingressroute.yaml
patches:
  - path: argocd-image-updater-patch.yaml
  - path: argocd-image-updater-config-patch.yaml
