apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - https://raw.githubusercontent.com/argoproj-labs/argocd-image-updater/stable/config/install.yaml
  - argocd-image-updater-config.yaml
  - sealed-secrets.yaml
  - repo-mobilebrain-manifests-sealed-secrets.yaml
  - argocd-notifications-sealed-secrets.yaml
  - argocd-traefik-ingressroute.yaml
  - repo-mobilebrain-manifests-sealed-secrets.yaml
patchesStrategicMerge:
  - argocd-image-updater-patch.yaml
